services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: keycloakdb
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: ${POSTGRES_USERNAME}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend

  user-service:
    image: user-service:latest
    build:
        context: ./UserService
        dockerfile: Dockerfile
    depends_on:
        - postgres
    ports:
        - "8090:8090"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userdb
        - DATASOURCE_USER=${POSTGRES_USERNAME}
        - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
        - predman-network

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local