server:
  port: 8090

grpc:
  server:
    port: 9090

spring:
  application:
    name: UserService

  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/postgres}
    username: ${DATASOURCE_USER:admin}
    password: ${DATASOURCE_PASSWORD:admin}
